DROP TABLE orders
DROP TABLE customers
DROP TABLE pc_tests
DROP TABLE employees
DROP TABLE pc_types
DROP TABLE cpu_types
DROP TABLE hard_drive_types
DROP TABLE keyboard_types
DROP TABLE motherboard_types
DROP TABLE power_supply_types
DROP TABLE ram_types
DROP TABLE products