DROP TABLE pc_type_order_details
DROP TABLE pc_types
DROP TABLE ram_types
DROP TABLE power_supply_types
DROP TABLE motherboard_types
DROP TABLE cpu_types
DROP TABLE hard_drive_types
DROP TABLE peripheral_order_details
DROP TABLE peripherals
DROP TABLE orders
DROP TABLE employees
DROP TABLE customers
