DROP TABLE PC_order_details
DROP TABLE PCs
DROP TABLE RAMs
DROP TABLE Power_supplies
DROP TABLE Motherboards
DROP TABLE CPUs
DROP TABLE HDDs
DROP TABLE Peripheral_order_details
DROP TABLE Peripherals
DROP TABLE Orders
DROP TABLE Employees
DROP TABLE Customers
